name: Publish to Winget

on:
  workflow_dispatch:

jobs:
  publish:
    # Action can only be run on windows
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Flow-Launcher.Flow-Launcher
          token: ${{ secrets.WINGET_TOKEN }}
